
spring:
  application:
    name: jwt-based-user-authentication-system
  security:
    jwt:
      secret-key: unN7T5xsIi19omKLLhe4ntESoLog+APlzBfW7hIVN7w=
      expiration-ms: 3600000

  datasource:
    username: root
    password: Mysql#1234
    url: jdbc:mysql://localhost:3306/mydatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:file:.env[.properties]

server:
  address: 0.0.0.0
  port: 8081
